# Clippy configuration
# Enforces stricter warnings as mentioned in CLAUDE.md

# Cognitive complexity thresholds
cognitive-complexity-threshold = 30
too-many-arguments-threshold = 7
type-complexity-threshold = 250
single-char-binding-names-threshold = 1

# Avoid false positives for common patterns
avoid-breaking-exported-api = true

# Allow some common patterns in this codebase
allowed-scripts = ["Latin"]
max-suggested-slice-pattern-length = 3

# Custom lint configuration
disallowed-names = ["foo", "baz", "quux", "lorem", "ipsum"]

# Performance-related settings
vec-box-size-threshold = 4096
pass-by-value-size-limit = 256
trivial-copy-size-limit = 256