[default]
extend-ignore-identifiers-re = [
    # Technical terms and proper nouns
    "tokio",
    "sqlx",
    "ChunkHound",
    "clippy",
    "rustfmt",
    "MSRV",
    "uuid",
    "async",
    "await",
    # File extensions and technical formats
    "yml",
    "toml",
    "json",
    "bincode",
    "bjall",
    # Database and storage terms
    "embeddings",
    "lancedb",
    "duckdb"
]

[default.extend-words]
# Add common technical terms that might be flagged
retriever = "retriever"
janet = "janet"