//! Index consistency checking for janet-ai-retriever
//!
//! This module provides data structures for validating the consistency of the search index,
//! including checking for orphaned chunks, missing embeddings, and data integrity issues.
//! Used by the status API to provide detailed diagnostics about index health.
//!
//! ## Key Components
//!
//! - **IndexConsistencyReport**: Complete consistency check results
//! - **ConsistencyCheck**: Individual check results with issue details
//! - **IssuesSummary**: Summary of all issues found during checks
//! - **ConsistencyStatus**: Health status enumeration
//!
//! ## Usage
//!
//! ```rust
//! use janet_ai_retriever::status::consistency::{IndexConsistencyReport, ConsistencyStatus};
//!
//! // Report would typically be generated by the status API
//! let report = IndexConsistencyReport {
//!     overall_status: ConsistencyStatus::Healthy,
//!     checks_performed: vec![],
//!     issues_summary: Default::default(),
//!     check_timestamp: chrono::Utc::now().timestamp(),
//! };
//! ```

use serde::{Deserialize, Serialize};

/// Complete consistency check results. See module docs for usage examples.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IndexConsistencyReport {
    /// Overall consistency status
    pub overall_status: ConsistencyStatus,
    /// Checks performed
    pub checks_performed: Vec<ConsistencyCheck>,
    /// Summary of issues found
    pub issues_summary: IssuesSummary,
    /// Timestamp when check was performed
    pub check_timestamp: i64,
}

/// Health status levels for consistency checks. See module docs for details.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ConsistencyStatus {
    Healthy,
    Warning,
    Critical,
}

/// Individual consistency check results. See module docs for details.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConsistencyCheck {
    /// Name of the check
    pub check_name: String,
    /// Check status
    pub status: ConsistencyStatus,
    /// Description of what was checked
    pub description: String,
    /// Number of items checked
    pub items_checked: usize,
    /// Number of issues found
    pub issues_found: usize,
    /// Details about issues (if any)
    pub issue_details: Vec<String>,
}

/// Summary of all issues found during consistency checks. See module docs for usage.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct IssuesSummary {
    /// Total issues found
    pub total_issues: usize,
    /// Critical issues requiring immediate attention
    pub critical_issues: usize,
    /// Warning issues that should be addressed
    pub warning_issues: usize,
    /// Recommendations for fixing issues
    pub recommendations: Vec<String>,
}
