//! Filesystem monitoring and change detection for janet-ai-retriever
//!
//! This module provides data structures for reporting filesystem monitoring status,
//! file change events, and stale file detection. Used by the status API to provide
//! detailed diagnostics about the file watching system and index freshness.
//!
//! ## Key Components
//!
//! - **FileSystemStatus**: Overall filesystem monitoring health and activity
//! - **FileChangeEvent**: Individual file change events with processing status
//! - **StaleFilesInfo**: Analysis of files that may need reindexing
//! - **StaleFileEntry**: Individual stale file information with priority
//!
//! ## Usage
//!
//! ```rust
//! use janet_ai_retriever::status::filesystem::{FileSystemStatus, FileChangeEvent};
//!
//! // Status would typically be generated by the filesystem monitoring subsystem
//! let status = FileSystemStatus {
//!     file_watching_active: true,
//!     directories_monitored: 5,
//!     watcher_error_count: 0,
//!     last_change_event_timestamp: Some(chrono::Utc::now().timestamp()),
//!     supported_file_systems: vec!["ext4".to_string(), "ntfs".to_string()],
//!     base_directory_fs_type: Some("ext4".to_string()),
//!     recent_events: vec![],
//! };
//! ```

use serde::{Deserialize, Serialize};

/// Filesystem monitoring status and activity. See module docs for usage examples.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileSystemStatus {
    /// Is file watching currently active?
    pub file_watching_active: bool,
    /// Number of directories being monitored
    pub directories_monitored: usize,
    /// File watcher error count
    pub watcher_error_count: usize,
    /// Last file change event timestamp
    pub last_change_event_timestamp: Option<i64>,
    /// Supported file system types
    pub supported_file_systems: Vec<String>,
    /// File system type of base directory
    pub base_directory_fs_type: Option<String>,
    /// Recent file change events (last 10)
    pub recent_events: Vec<FileChangeEvent>,
}

/// Individual file change event with processing status. See module docs for details.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileChangeEvent {
    /// Event type (Created, Modified, Deleted, etc.)
    pub event_type: String,
    /// File path that changed
    pub file_path: String,
    /// Timestamp when event occurred
    pub timestamp: i64,
    /// Whether the event was processed successfully
    pub processed_successfully: bool,
}

/// Analysis of files that may need reindexing. See module docs for usage examples.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StaleFilesInfo {
    /// Files modified after last index update
    pub modified_files: Vec<StaleFileEntry>,
    /// Files added but not yet indexed
    pub unindexed_files: Vec<StaleFileEntry>,
    /// Files deleted but still in index (estimated)
    pub deleted_files_in_index: Vec<StaleFileEntry>,
    /// Recommended reindex candidates
    pub reindex_candidates: Vec<String>,
    /// Total estimated stale files count
    pub total_stale_count: usize,
}

/// Individual stale file entry with reindexing priority. See module docs for details.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StaleFileEntry {
    /// File path
    pub file_path: String,
    /// Last modified timestamp
    pub last_modified_timestamp: Option<i64>,
    /// Reason for being considered stale
    pub staleness_reason: String,
    /// Priority for reindexing (1-10, higher is more urgent)
    pub reindex_priority: u8,
}
