//! Network connectivity diagnostics for janet-ai-retriever
//!
//! This module provides data structures for monitoring network connectivity to external
//! services like HuggingFace Hub for model downloads. It includes proxy configuration
//! status, SSL validation, and overall network health assessment.
//!
//! ## Key Components
//!
//! - **NetworkStatus**: Overall network health and external service connectivity
//! - **ConnectivityStatus**: Individual service reachability and response times
//! - **ProxyStatus**: HTTP proxy configuration and authentication status
//! - **NetworkHealth**: Overall network health enumeration
//!
//! ## Usage
//!
//! ```rust
//! use janet_ai_retriever::status::network::{NetworkStatus, ConnectivityStatus, NetworkHealth};
//!
//! // Status would typically be generated by network diagnostic checks
//! let status = NetworkStatus {
//!     model_download_connectivity: ConnectivityStatus {
//!         is_reachable: true,
//!         last_successful_connection: Some(chrono::Utc::now().timestamp()),
//!         error_message: None,
//!         response_time_ms: Some(250),
//!     },
//!     hugging_face_hub_access: ConnectivityStatus {
//!         is_reachable: true,
//!         last_successful_connection: Some(chrono::Utc::now().timestamp()),
//!         error_message: None,
//!         response_time_ms: Some(180),
//!     },
//!     proxy_configuration: Default::default(),
//!     ssl_certificate_validation: true,
//!     overall_network_health: NetworkHealth::Healthy,
//! };
//! ```

use serde::{Deserialize, Serialize};

/// Overall network status for external dependencies. See module docs for usage examples.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NetworkStatus {
    /// Model download connectivity
    pub model_download_connectivity: ConnectivityStatus,
    /// Hugging Face Hub access
    pub hugging_face_hub_access: ConnectivityStatus,
    /// Proxy configuration status
    pub proxy_configuration: ProxyStatus,
    /// SSL certificate validation status
    pub ssl_certificate_validation: bool,
    /// Overall network health
    pub overall_network_health: NetworkHealth,
}

/// Individual service connectivity status. See module docs for details.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConnectivityStatus {
    /// Is the service reachable?
    pub is_reachable: bool,
    /// Last successful connection timestamp
    pub last_successful_connection: Option<i64>,
    /// Error message if unreachable
    pub error_message: Option<String>,
    /// Response time in milliseconds for last check
    pub response_time_ms: Option<u64>,
}

/// HTTP proxy configuration status. See module docs for details.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct ProxyStatus {
    /// Is proxy configured?
    pub proxy_configured: bool,
    /// Proxy host and port
    pub proxy_address: Option<String>,
    /// Proxy authentication status
    pub proxy_auth_configured: bool,
}

/// Overall network health levels. See module docs for usage examples.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum NetworkHealth {
    Healthy,
    Limited,
    Offline,
}
