[package]
name = "janet-context"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1"
clap = { version = "4.5.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bin]]
name = "janet-context-cli"
path = "src/bin/janet_context_cli.rs"
