#![allow(dead_code)]

// Much of the code is used by the MCP server tools, which foul the static analysis
use crate::ServerConfig;
use crate::tools::{self, regex_search::RegexSearchRequest};
use anyhow::Result;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::model::{Implementation, ProtocolVersion, ServerCapabilities};
use rmcp::{
    ErrorData as McpError, ServerHandler, ServiceExt,
    handler::server::tool::ToolRouter,
    model::{CallToolResult, Content, ServerInfo},
};
use tokio::io::{stdin, stdout};
use tracing::info;

/// Janet MCP Server that provides search capabilities across codebases.
///
/// This server implements the Model Context Protocol (MCP) to provide AI tools
/// with advanced search capabilities over indexed codebases. It combines:
/// - **Regex search**: Fast pattern-based text search with context
/// - **Semantic search**: AI-powered similarity search using embeddings
/// - **Status reporting**: Comprehensive system health and configuration info
///
/// The server requires a pre-built index database created by janet-ai-retriever.
/// It communicates with MCP clients (like Claude Desktop) over stdio using
/// the standard MCP protocol.
///
/// # Architecture
/// ```text
/// MCP Client (Claude) ↔ stdio ↔ JanetMcpServer ↔ IndexingEngine ↔ SQLite DB
///                                        ↓
///                                 EnhancedFileIndex
/// ```
#[derive(Clone, Debug)]
pub struct JanetMcpServer {
    config: ServerConfig,
    tool_router: ToolRouter<Self>,
}

#[rmcp::tool_router]
impl JanetMcpServer {
    /// Create a new Janet MCP server with the given configuration.
    ///
    /// This initializes the server with all necessary components for providing
    /// search capabilities. The server requires an existing `.janet-ai.db` index
    /// file in the root directory - use janet-ai-retriever to create this first.
    ///
    /// # Arguments
    /// * `config` - Server configuration specifying the root directory
    ///
    /// # Returns
    /// A new JanetMcpServer instance ready to serve MCP requests
    ///
    /// # Errors
    /// - If the `.janet-ai.db` index file is not found in the root directory
    /// - Database connection or initialization errors
    /// - IndexingEngine initialization errors
    ///
    /// # Example
    pub async fn new(config: ServerConfig) -> Result<Self> {
        info!(
            "Initializing Janet MCP server with root: {:?}",
            config.root_dir
        );
        // Aggressively simplified server: no indexing/embedding initialization.
        // This server now only supports lightweight tools (regex_search).
        Ok(Self {
            config,
            tool_router: Self::tool_router(),
        })
    }

    /// Status tool - comprehensive system status and debugging information
    #[rmcp::tool(
        description = "Show comprehensive system status including index health, configuration, performance metrics, and troubleshooting information"
    )]
    async fn status(&self) -> Result<CallToolResult, McpError> {
        info!("Processing simplified status request");

        // Simplified status: report configuration and note removed features.
        let status_text = format!(
            "Janet MCP Server Status\n\nRoot Dir: {:?}\nFeatures: regex_search only (semantic/indexing removed)\n",
            &self.config.root_dir
        );

        Ok(CallToolResult::success(vec![Content::text(status_text)]))
    }

    /// Regex search tool - search project files, dependencies, and docs
    #[rmcp::tool(
        description = "Search files using regex patterns across project files, dependencies, and autogenerated docs"
    )]
    async fn regex_search(
        &self,
        Parameters(request): Parameters<RegexSearchRequest>,
    ) -> Result<CallToolResult, McpError> {
        match tools::regex_search::regex_search(&self.config, request).await {
            Ok(result) => Ok(CallToolResult::success(vec![Content::text(result)])),
            Err(err) => Err(McpError::internal_error(err, None)),
        }
    }

    /// Serve the MCP server using stdio transport
    /// Start serving MCP requests over stdio transport.
    ///
    /// This method starts the MCP server and begins listening for requests over
    /// standard input/output. This is the standard transport mechanism for MCP
    /// servers when integrated with clients like Claude Desktop.
    ///
    /// The server will continue running until it receives a shutdown signal or
    /// encounters an error. All MCP protocol messages are handled automatically.
    ///
    /// # Returns
    /// `Ok(())` when the server shuts down gracefully
    ///
    /// # Errors
    /// - MCP protocol communication errors
    /// - Stdin/stdout transport errors
    /// - Tool execution errors
    ///
    /// # Example
    pub async fn serve_stdio(self) -> Result<()> {
        info!("Starting MCP server with stdio transport");

        let transport = (stdin(), stdout());
        let server = self.serve(transport).await?;
        let quit_reason = server.waiting().await?;

        info!("MCP server quit: {:?}", quit_reason);
        Ok(())
    }
}

#[rmcp::tool_handler]
impl ServerHandler for JanetMcpServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo {
            protocol_version: ProtocolVersion::LATEST,
            capabilities: ServerCapabilities::builder().enable_tools().build(),
            server_info: Implementation::from_build_env(),
            instructions: Some(
                "Janet AI MCP Server - provides regex search capabilities across codebases".into(),
            ),
        }
    }
}
