name: Conventional Commits

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  conventional-commits:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Check Conventional Commits
      uses: webiny/action-conventional-commits@v1.3.0
      with:
        allowed-commit-types: "feat,fix,docs,style,refactor,perf,test,chore,ci,build,revert"
        allow-merge-commits: true
        allow-revert-commits: true

  pr-title-check:
    name: PR Title Check
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - name: Check PR title
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: |
          feat
          fix
          docs
          style
          refactor
          perf
          test
          chore
          ci
          build
          revert
        scopes: |
          janet-context
          janet-retriever
          storage
          ci
          docs
        requireScope: false
        disallowScopes: |
          release
        subjectPattern: ^(?![A-Z]).+$
        subjectPatternError: |
          The subject "{subject}" found in the pull request title "{title}"
          didn't match the configured pattern. Please ensure that the subject
          doesn't start with an uppercase character.
        wip: true
        validateSingleCommit: false